// Wellness wheel content: the 8 dimensions, the 64-question assessment, the
// 8-week activity plan, bonus challenges, badges, and level thresholds.
// Written for family caregivers of someone with a rare disease specifically,
// not generic wellness content — grounded in what's actually reported in
// caregiver research (isolation, chronic/anticipatory grief, income and
// career disruption, becoming disease-literate, home-as-care-environment,
// real financial strain).
// Sky & Tide palette: each dimension gets a muted colour + tint at similar
// lightness so the wheel reads as one harmonious family (per the Sky & Tide
// design handoff; dimension names stay the course's own eight).
export const WEDGE_CONFIG = {
  Social:        { color: "#8E9AC8", light: "#E4E4EF", icon: "social" },
  Occupational:  { color: "#4A7690", light: "#D6E2EA", icon: "occupational" },
  Environmental: { color: "#6E8570", light: "#DFE7DC", icon: "environmental" },
  Intellectual:  { color: "#7CA7C4", light: "#DCE8EF", icon: "intellectual" },
  Spiritual:     { color: "#8093A6", light: "#E1E5EC", icon: "spiritual" },
  Emotional:     { color: "#C98F97", light: "#F0DEE0", icon: "emotional" },
  Physical:      { color: "#5FA0A0", light: "#D9E8E5", icon: "physical" },
  Financial:     { color: "#CDA66B", light: "#F0E6D2", icon: "financial" },
};
export const WEDGES = Object.keys(WEDGE_CONFIG);

export const QUESTIONS = {
  Social: ["I have at least one person in my life who understands what caregiving for my situation actually involves.","I make time for relationships that have nothing to do with caregiving, even briefly.","I feel part of a community, whether that's other caregivers, family, or friends who show up.","I can say no to a request without guilt, even when someone is used to me saying yes.","When I'm struggling, I reach out rather than handling it alone.","My relationship with my partner, if I have one, gets attention beyond logistics and caregiving admin.","I've stayed in touch with at least one friendship this month that isn't about caregiving.","Being around people leaves me with more energy than it costs me, more often than not."],
  Occupational: ["I recognise caregiving itself as real work, not just \"what needs to be done.\"","If I'm employed, I've been able to adapt my work around caregiving without abandoning it entirely.","I feel more in control of my daily workload, paid work, caregiving, or both, than at the mercy of it.","I've told someone, an employer, a colleague, a family member, what I actually need to make things workable.","I get some acknowledgement for what I do, from myself if from no one else.","I'm not just surviving my responsibilities; I'm building something in them too, skills, insight, purpose.","My sense of who I am hasn't been entirely replaced by \"caregiver.\"","I end most days feeling like I did something that mattered, not just something that had to be done."],
  Environmental: ["My home functions well for the caregiving it needs to hold, without being only about that.","I have a space, even a small one, that belongs to me and not to the caregiving routine.","I get outside or into fresh air regularly, not just when there's time left over.","I feel safe and steady in my physical surroundings, not on edge.","I notice when my environment is adding to my stress, and I do something about it when I can.","My home has small things in it that are just for beauty or comfort, not function.","I have some kind of regular access to a change of scenery, even briefly.","I feel connected to where I live, not just like I'm passing through it."],
  Intellectual: ["I have at least one interest or pursuit that has nothing to do with managing anyone's health.","I make time to learn or engage with something new, even briefly, most weeks.","I have a creative outlet, however small, that I actually use.","My mind gets to be curious sometimes, not just vigilant.","I have conversations that stretch my thinking, not just logistics and updates.","I take in things, books, shows, podcasts, ideas, that have nothing to do with caregiving.","When I solve problems, it's more often with curiosity than with anxiety.","My intellectual life feels like it's still mine, not just reactive to whatever comes up."],
  Spiritual: ["I have a clear sense of what actually matters most to me right now.","I make time, even a few minutes, for stillness or reflection most days.","I have something, faith, values, practice, that holds steady when things don't make sense.","I can sit with uncertainty about the future without it undoing me.","I feel some sense of purpose in how I'm spending this season of my life, even amid the hard parts.","I have space to grieve what's been lost or changed, not just push through.","I allow myself moments of meaning or gratitude, even in a hard week.","My inner life gets tended to, not just set aside for later."],
  Emotional: ["I can name what I'm actually feeling, most days, even when it's complicated.","I have somewhere to put difficult feelings, rather than carrying them alone.","I give myself permission to grieve what's changed, even without a single clear loss to point to.","I don't feel guilty for needing rest or support, even when I still feel it.","I talk to myself kindly, especially on the days I feel like I'm failing at this.","I let myself feel joy or lightness without it feeling like a betrayal of how hard things are.","I ask for support before I'm completely depleted, not just after.","I feel steadier emotionally than I did a month ago, even slightly."],
  Physical: ["I move my body in some way I enjoy most weeks, even briefly.","I get enough sleep most nights, or find ways to recover when I don't.","I eat in a way that gives me energy, most of the time.","I attend to my own medical care as consistently as I manage it for someone else.","I notice my body's signals (pain, fatigue, hunger) instead of overriding them by default.","I'm managing my own health conditions or symptoms, not just everyone else's.","I'm mindful about alcohol, caffeine, or other things I use to get through the day.","My energy feels adequate for the life I'm actually living, most days."],
  Financial: ["I have a realistic picture of what caregiving actually costs our family, not just a general sense.","I know what financial assistance or support programs might be available to us.","Financial stress doesn't dominate my thinking most days, even if it's present.","I feel some sense of control over financial decisions, rather than just reacting to bills as they come.","I've had at least one honest conversation about money with someone I trust.","I'm not carrying financial decisions or knowledge alone, if I have a partner or family to share them with.","I can talk about money without shame, even when things are tight.","I feel like I have some financial choices left, even if they're small ones."],
};

// 8 weeks × 3 activities per dimension, written for the same caregiver
// audience as QUESTIONS above.
export const ACTIVITIES = {
  Social: [["Message one person who's been on your mind, just to check in","Say yes to one small social moment this week: a coffee, a call, a text back","Name one person who actually understands your situation, and reach out to them"],["Have one conversation this week that isn't about caregiving logistics","Ask for a specific piece of help from someone, instead of managing alone","Spend 15 minutes with your partner or a close friend, phones away"],["Reconnect with one relationship that's gone quiet since things got busy","Join or revisit one group, in person or online, connected to your situation or interests","Tell someone specifically what their support has meant to you"],["Set one boundary this week with someone who assumes you're always available","Do one thing with a sibling, partner, or other family member that's just for the two of you","Accept help when it's offered, instead of saying \"I've got it\""],["Plan one thing to look forward to with someone else, even small","Have one honest conversation about how you're actually coping","Thank someone who has quietly shown up for you"],["Reflect: who has been steady for you through this stretch? Let them know","Identify one relationship you want to invest in going forward","Celebrate a connection that's gotten you through a hard week"],["Reach out to someone new who could become part of your support system","Say yes to a social invitation you'd usually decline out of tiredness","Check in on another caregiver the way you'd want someone to check in on you"],["Notice how your circle has changed since week 1, and name one shift out loud","Make a plan for keeping one relationship going once this programme ends","Tell someone specific what their support has meant to you these two months"]],
  Occupational: [["Write down three things caregiving has taught you that count as real skills","Identify one task this week you can hand to someone else, even partially","Name one part of your work or role that still feels like yours"],["Have one conversation about what flexibility you actually need, at work or at home","Protect one hour this week that's just for a task you find meaningful","Acknowledge one thing you handled well, out loud or in writing"],["Identify what's draining you most in your workload right now, and name it plainly","Ask for help with one specific task instead of absorbing it","Do one thing this week that uses a strength that has nothing to do with caregiving"],["Set a clear start or stop point for one part of your day","Have a direct conversation about expectations, at work or within the family","Write a \"done\" list at the end of one day instead of only a to-do list"],["Explore one resource, support, or piece of information that could lighten your load","Ask someone you trust for honest feedback on how you're managing","Protect one break today, even ten minutes, without guilt"],["Write one sentence about what you want your role, paid or unpaid, to look like next","Identify one thing about your current load you want to change going forward","Acknowledge a milestone you've reached, however small it looks from outside"],["Revisit a boundary you set earlier in this programme: is it still holding, does it need adjusting","Take on one task that stretches a skill you want to keep building","Say out loud, or write down, one thing you're proud of handling this stretch"],["Write down how your relationship with work or role has shifted since week 1","Decide one working pattern from these 8 weeks you want to keep for good","Acknowledge the person who started this programme, and how far she's come"]],
  Environmental: [["Spend 15 minutes outside today, even if it's just the yard or a nearby street","Clear one small surface that's been bothering you","Add one thing to your space that's just for you: a candle, a photo, a plant"],["Find ten minutes in a space that's just yours, even a corner or a car","Do a small digital declutter: one folder, one inbox, one photo album","Notice one thing in your environment that drains you, and change what you can"],["Spend time somewhere with a different view this week: a park, a friend's place, a drive","Tidy one space that affects how you feel each morning","Identify what your ideal home environment would feel like, and take one small step toward it"],["Set up or reclaim one small space that's just for rest or quiet","Spend a few minutes somewhere with no agenda, no task attached","Make one small change that makes mornings or evenings easier"],["Adjust one thing about your sleep environment: light, noise, temperature","Visit somewhere outdoors that isn't part of your usual routine","Reorganise one area so it better supports the days you actually have"],["Do a small seasonal reset: one drawer, one shelf, one bag","Add one lasting touch of comfort or beauty to your space","Reflect: does your home support the person you're becoming, or just the tasks you do?"],["Make one more change to your space based on what's actually helped these past weeks","Return to the outdoor spot that's worked best for you this programme","Check: is your home still supporting you, or has something crept back in"],["Walk through your home and notice what's different since week 1","Choose one environmental habit to keep protecting after this programme ends","Add one lasting marker to your space, something that reminds you what you built here"]],
  Intellectual: [["Read or listen to something for 15 minutes that has nothing to do with caregiving","Start a simple log of one thing you're curious about lately","Pick one small creative outlet to return to this week: drawing, writing, music, cooking"],["Learn one small new thing, a recipe, a skill, a fact, that has nothing to do with your caregiving role","Have one conversation about something other than logistics or health updates","Do a puzzle, game, or something that occupies your mind playfully"],["Read or watch one full piece of long-form content, start to finish","Revisit an interest you used to have and dropped","Write for 10 minutes about anything except caregiving"],["Start or continue a small creative project, just for you","Ask someone about something they know well, and actually listen","Notice one moment this week where curiosity showed up instead of worry"],["Try something outside your usual genre or routine: a book, a show, an activity","Write down three questions you're genuinely curious about","Take a short break to learn something with zero practical use"],["Reflect on one thing you've learned about yourself so far","Identify one interest you want to protect time for going forward","Share something you're excited about with someone else"],["Finish something you started weeks ago and never got back to","Try one more new thing before this programme wraps: a book, a class, a skill","Notice how your curiosity has shown up more often lately, and name one example"],["Reflect on what you've learned about yourself these 8 weeks","Choose one interest to keep protecting time for once this programme ends","Write a short list of what you want to explore next"]],
  Spiritual: [["Spend 5 minutes in silence or stillness this morning","Write down what matters most to you right now, in one sentence","Notice one moment of meaning today, however small"],["Start a short gratitude note: three things, each evening this week","Spend time outdoors with intention, not as exercise, just presence","Name one place where your daily life and your values feel out of step"],["Take 10 minutes to breathe or sit quietly, without your phone","Read, listen to, or reflect on something that nourishes you, not informs you","Let go of one obligation this week that isn't truly yours to carry"],["Create one small ritual, morning, evening, or weekly, that's just yours","Reflect on what's giving your life meaning right now, even in a hard season","Do one generous thing with no expectation of anything back"],["Write a short letter to your future self, a few months or years from now","Sit with one hard question without rushing to resolve it","Spend a few minutes doing absolutely nothing: no task, no screen, no purpose"],["Reflect on what you want to carry forward from this stretch","Revisit what matters most to you: has anything shifted?","Write one intention for the weeks ahead, however small"],["Return to the ritual or practice that's worked best for you, and repeat it deliberately","Sit with what's shifted in how you make meaning of this season","Do one act of generosity that costs you nothing but attention"],["Write a letter to the version of you that started this programme","Name what you want to carry forward once the structure of these weeks ends","Mark the end of this stretch with one small, deliberate ritual"]],
  Emotional: [["Name your emotional state honestly this morning, even just to yourself","Identify one feeling you've been avoiding, and just acknowledge it","Do one small thing today purely because it makes you feel good"],["Set aside 10 minutes for something gentle that helps you reset","Tell one person how you're actually doing, not the polished version","Write down what tends to trigger your hardest moments"],["Write yourself a short, kind note after a hard moment this week","Let go of one source of stress that isn't essential right now","Do something a little playful or silly, just because"],["Notice one pattern in how you respond when things go wrong","Let yourself fully feel something this week: grief, laughter, relief, whatever it is","Ask for help with one thing you've been carrying alone"],["Build a small emotional first-aid kit: a song, a walk, a person, a phrase","Name one strength in yourself that you tend to overlook","Have one honest conversation you've been putting off"],["Reflect on how your emotional load has shifted so far","Identify one belief about yourself you're ready to update","Acknowledge how far you've come, not just how far there is to go"],["Notice a hard moment this week, and respond to yourself the way you would a friend","Name one emotional pattern that's actually shifted since week 1","Let yourself feel proud, not just relieved, about something you've carried"],["Reflect honestly on your emotional load compared to eight weeks ago","Identify one support you want to keep in place after this programme ends","Write down what you'd tell another caregiver starting where you started"]],
  Physical: [["Move your body for 20 minutes in a way you actually enjoy","Drink water consistently through the day, not just when you remember","Go to bed 20 minutes earlier one night this week"],["Try one different form of movement this week: a walk, a stretch, a dance in the kitchen","Add one more vegetable or piece of fruit to a meal","Have one screen-free hour before bed"],["Get outside and walk, even ten minutes, every day this week","Prepare one meal from scratch, even something simple","Book or schedule a health check-up for yourself that you've been putting off"],["Do 10 minutes of stretching or gentle movement","Notice your caffeine or alcohol intake this week, without judgement","Track your sleep for a few nights and notice one pattern"],["Look for small ways to move more: stairs, a longer walk, standing breaks","Eat one meal slowly, without screens","Do one restorative thing for your body: a bath, a stretch, an early night"],["Reflect on how your body feels compared to when you started","Choose one physical habit from these weeks to keep going","Do something today that celebrates what your body has carried you through"],["Keep going with whatever movement has actually stuck these past weeks","Notice one physical habit that's genuinely easier now than in week 1","Follow through on one piece of your own health care you've been meaning to book"],["Compare how your body feels now to how it felt at the start","Choose one physical habit from these 8 weeks to protect for good","Do something today that marks how far your body has carried you"]],
  Financial: [["Look at last month's spending with curiosity, not judgement","Identify one non-essential expense and decide if it still fits","Set one small, realistic savings or budget goal for the week"],["Review or start a simple budget that reflects your actual life right now","Look into one financial assistance or support program that might apply to you","Have one honest conversation about money with someone you trust"],["Spend 15 minutes on one piece of financial information relevant to your situation","Identify one financial decision you've been avoiding, and take one small step on it","Cancel or pause one subscription or expense you don't need"],["Check in on savings, insurance, or benefits relevant to your family's situation","Identify one recurring expense you could reduce","Write down what financial security would actually look like for you"],["Make a plan for one financial goal, however modest: a buffer, a bill, a break","Check your overall financial picture: accounts, benefits, what's coming up","Name one belief about money you inherited that may not be serving you"],["Acknowledge one financial win from these past weeks, however small","Set one financial intention for the next few months","Reflect: does your spending, right now, reflect what actually matters to you?"],["Check in on the financial habit or plan you started weeks ago: is it holding","Have one more honest conversation about money before this programme wraps","Look into one further piece of support you haven't explored yet"],["Look back at your financial picture compared to week 1: what's changed","Set one financial intention to carry past this programme","Acknowledge one financial win, however small, from these 8 weeks"]],
};

// Icon is drawn from the challenge's own wedge (WEDGE_CONFIG) at render time,
// keeping every icon in the tool traceable to the same 8-dimension system.
export const BONUS_CHALLENGES = [
  { id: "b1", wedge: "Physical", text: "Complete a 7-day movement streak, any movement, every day.", points: 50 },
  { id: "b2", wedge: "Social", text: "Organise one gathering, however small, with people who understand your situation.", points: 40 },
  { id: "b3", wedge: "Emotional", text: "Write a 500-word letter about the hardest part of this, to yourself or no one. You don't have to send it.", points: 45 },
  { id: "b4", wedge: "Financial", text: "Track every dollar spent on caregiving costs specifically for one full week.", points: 50 },
  { id: "b5", wedge: "Intellectual", text: "Finish one book that has nothing to do with health, caregiving, or your condition.", points: 40 },
  { id: "b6", wedge: "Spiritual", text: "Spend 20 minutes a day this week in intentional stillness or reflection.", points: 45 },
  { id: "b7", wedge: "Environmental", text: "Arrange real respite for one full day: someone else covers care, no screens, no obligations for you.", points: 40 },
  { id: "b8", wedge: "Occupational", text: "Take one full day genuinely off, from paid work or caregiving admin, and let yourself rest.", points: 50 },
];

// Each badge is a hand-drawn medallion (see BadgeMedallion in components.jsx),
// locked in muted stone tones and switching to the Antique Brass "earned"
// treatment only once unlocked — the achievement color is reserved for this
// moment.
export const BADGES = [
  { id: "first_step",  name: "First Step",      icon: "leaf", desc: "Completed the assessment" },
  { id: "week1",       name: "One Week Strong",  icon: "target", desc: "Completed all Week 1 activities" },
  { id: "streak3",     name: "On a Roll",        icon: "flame", desc: "3-day activity streak" },
  { id: "halfway",     name: "Halfway There",    icon: "moon", desc: "Completed Week 4" },
  { id: "all_wedges",  name: "Full Circle",      icon: "mark", desc: "Completed an activity in every wedge" },
  { id: "finisher",    name: "Journey Complete", icon: "medal", desc: "Completed all 8 weeks" },
  { id: "streak7",     name: "Unstoppable",      icon: "sparkle", desc: "7-day activity streak" },
  { id: "inner3",      name: "Inner Work",       icon: "spiritual", desc: "Completed 3 Spiritual or Emotional activities" },
  { id: "bonus1",      name: "Over-Achiever",    icon: "sparkle", desc: "Completed a bonus challenge" },
  { id: "buddy",       name: "Better Together",  icon: "partnership", desc: "Shared your wheel with an accountability partner" },
  { id: "check_in8",   name: "Honest Reflection", icon: "document", desc: "Completed 8 weekly check-ins" },
  { id: "reassessed",  name: "Growth Visible",   icon: "chart", desc: "Completed the 8-week reassessment" },
];

export function scoreWedge(answers) {
  return Math.round((answers.reduce((a,b)=>a+b,0) / (answers.length * 5)) * 100);
}
export function getLevel(score) {
  if (score >= 80) return { label: "Nourished",        color: "#4A7690" };
  if (score >= 60) return { label: "Cared For",        color: "#5FA0A0" };
  if (score >= 40) return { label: "Steady",           color: "#CDA66B" };
  return            { label: "Stretched Thin",  color: "#C98F97" };
}
export const LEVEL_THRESHOLDS = [
  { min: 0,   label: "Seed",     icon: "leaf",    color: "#8093A6" },
  { min: 100, label: "Sprout",   icon: "plant",   color: "#5FA0A0" },
  { min: 250, label: "Bloom",    icon: "spiritual", color: "#4A7690" },
  { min: 500, label: "Flourish", icon: "sparkle", color: "#CDA66B" },
  { min: 800, label: "Radiant",  icon: "medal",   color: "#A5813C" },
];
export function getUserLevel(pts) {
  return LEVEL_THRESHOLDS.reduce((l,t) => pts >= t.min ? t : l, LEVEL_THRESHOLDS[0]);
}
